---
user_info:
  - { name: james, firstname: James, lastname: Jockey, password: redhat@123, email: james@ad1.a3dc.example.opentlc.com, group_name: dev, group_scope: domainlocal }
  - { name: bill, firstname: Bill, lastname: Gates, password: redhat@123, email: bill@ad1.a3dc.example.opentlc.com, group_name: dev, group_scope: domainlocal }
  - { name: mickey, firstname: Mickey, lastname: Mouse, password: redhat@123, email: mickey@ad1.a3dc.example.opentlc.com, group_name: qa, group_scope: domainlocal }
  - { name: donald, firstname: Donald, lastname: Duck, password: redhat@123, email: donald@ad1.a3dc.example.opentlc.com, group_name: qa, group_scope: domainlocal }
