---
# tasks file for win_ad_install
- name: Install AD Domain Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Set up AD Controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
        
- name: Reboot windows server
  win_reboot:
    reboot_timeout: 600

- name: Print out Domain list
  win_command: nltest /dclist:"{{ ad_domain_name }}"    
  register: result

- name: return output of win_command
  debug:
    var: result.stdout
